### ISSUE TITLE
Populate On Home Page (from to-do list)

### ISSUE THREAD

**Issue by danciucu** [danciucu/Xtractor#8]
- [x]  Structure ID (B1)
- [x]  Month Interval (C5)
- [x] Route # / Name (B7 / C7)
- [x] Posting Info (E9, E12-E19)
- [x] Bridge / Culvert (B14) -> Ensure L2-L6 Populate Properly
- [x] Beam Lines - AI down the road? (B16)
- [x] Previous Ratings (B25, B28, B31, B34, B49)
- [x] Scour Observed (E20)
- [x] Previous Work Items (A60:G69)

**Comment by allen-cantrell** [comment]
#3
